### ISSUE TITLE
表格编辑的结合 element-ui下拉列表无法监听事件

### ISSUE THREAD

**Issue by tanzhuo81** [fall-zhang/vue-fantable#11]
fan-table 的版本：0.2.3

vue 的版本：3.x

使用的浏览器：chrome

问题的类型（issue or feature）：网站demo的表格编辑下的结合 element-ui中下拉列表不好用

对问题的详细说明：
![1716781721673](https://github.com/fall-zhang/vue-fantable/assets/15990569/867d7a81-e0a6-4686-beb9-d6bc18a4f140)

**Comment by tanzhuo81** [comment]
![1716793488277](https://github.com/fall-zhang/vue-fantable/assets/15990569/41e1158b-d88f-456b-91cd-a5fd4e205715)
问题解决了。麻烦作者改一下。

**Comment by fall-zhang** [comment]
好的，Vue3 中 JSX 事件确实需要小驼峰书写，demo 中的内容确实都还没有修改，这周会把所有涉及的部分一并修改

**Comment by fall-zhang** [comment]
问题已修复
