### ISSUE TITLE
复制、剪切、粘贴键盘快捷键只有在选中多个单元格时才有效

### ISSUE THREAD

**Issue by samaelxz** [fall-zhang/vue-fantable#2]
![image](https://github.com/fall-zhang/vue-fantable/assets/9568207/7a414fd3-9453-44a0-80b7-3fe6947935f0)
如图，似乎在单选的情况下，Ctrl+X, Ctrl+C, Ctrl+V快捷键是无效的，只有选中多个单元格时才生效

**Comment by fall-zhang** [comment]
我在测试的时候，并没有遇到该问题，是否已被修复，或者是事件冲突

**Comment by fall-zhang** [comment]
我在 0.1.9 中也发现了该问题，在更新到 0.2.1 后不存在该问题了，如果没有争议，将在一周内关闭该 issue
