### ISSUE TITLE
800条数据在unitable和vue-fanttable就直接卡顿了 难道只能分页吗？

### ISSUE THREAD

**Issue by lozn00** [fall-zhang/vue-fantable#4]
fan-table 的版本：

vue 的版本：3

使用的浏览器：

问题的类型（issue or feature）：

对问题的详细说明：

**Comment by lozn00** [comment]
我只配置了2个
```
  <fan-table :columns="columns" :table-data="tableData"/>
```

**Comment by lozn00** [comment]
虚拟的有问题，还望修复 
![image](https://github.com/fall-zhang/vue-fantable/assets/14260426/726187be-232f-4242-987d-74d1826be1ef)
我用在uniapp

**Comment by lozn00** [comment]
```
	<fan-table :columns="columns" :table-data="rows" :scroll-width="0" :virtual-scroll-option="{enable:true}"
		:max-height="300" row-key-field-name="rowKey"
		    :border-around="true"
		         :border-x="true"
		         :border-y="true"
				   :style="{'word-break':'keepall'}"
		 
		 />
```

**Comment by fall-zhang** [comment]
> ```
> 	<fan-table :columns="columns" :table-data="rows" :scroll-width="0" :virtual-scroll-option="{enable:true}"
> 		:max-height="300" row-key-field-name="rowKey"
> 		    :border-around="true"
> 		         :border-x="true"
> 		         :border-y="true"
> 				   :style="{'word-break':'keepall'}"
> 		 
> 		 />
> ```

更新到该配置后还有问题吗，我测试了一下，可以虚拟滚动了。

**Comment by lozn00** [comment]
已经弃坑了，在uniapp中性能极差，但是是官方的也是如此，unitable就30条都卡顿，问题不是出在翻页，实在头疼，我后面直接弄unitable加翻页 把1000条记录放在内存中然后临时取50 条这样子展示。 另外在app那边的话还好些，至于这个虚拟滚动感觉滑动有点毛病，所以我还是改成翻页的，

**Comment by lozn00** [comment]
app那边的话 uni table 30条就不卡，但是h5就卡，无语了

**Comment by lozn00** [comment]
期待兼容 移动端 uniapp的table出现，这个需要改很多样式才能搞得和unitable差不多的感觉，
不过里面的复制行啥的或许有用，需要复制一些数据粘贴到编辑框

**Comment by lozn00** [comment]
https://www.jianshu.com/p/269290ef3f0a?v=1712545775960

**Comment by fall-zhang** [comment]
我不太清楚 uni-app 具体工作细节，京东有个 [NutUI Table]( https://nutui.jd.com/3x/#/zh-CN/component/table) 不知道会不会对你的应用有帮助

**Comment by lozn00** [comment]
@fall-zhang  谢谢了，不过uni-table30条都有问题，我感觉换什么都是一样的，
