### ISSUE TITLE
能否使用vue-demi，来直接兼容vue2

### ISSUE THREAD

**Issue by endday** [fall-zhang/vue-fantable#6]
因为原vue-easytable的更新频率下降了
我想提个pr，能不能用vue-demi来兼容vue2的代码，就是一套源码打包出vue2和vue3两套代码
但是担心现在代码是否有针对vue3的改动，或者使用了vue3独有的api或特性？会不会有完全无法兼容的情况？

**Comment by fall-zhang** [comment]
因为我目前打算（正在）将代码转为 Typescript，以增强可维护性，使用 vue-demi 的内容可控性是否会变好值得商榷，目前版本应该可以做，但 1.0 （更新为 Typescript）之后，就不考虑兼容 vue2

**Comment by pkaq** [comment]
不就是因为原库不支持vue3才有的这个嘛 倒反天罡啊
